name: Checks

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  format:
    runs-on: ubuntu-latest
    container: ghcr.io/acts-project/format10:v15
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: CI/check_format .
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: changed
          path: changed
  format-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install black
        run: pip install black==22.3.0
      - name: Run black format check
        run: black --check . --extend-exclude ".*thirdparty.*"

  license:
    runs-on: ubuntu-latest
    container: python:alpine3.6
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: >
          apk add --no-cache git
          && CI/check_license.py . --exclude "*thirdparty/*"
  include_guards:
    runs-on: ubuntu-latest
    container: python:alpine3.6
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: >
          CI/check_include_guards.py . --fail-global --exclude "*thirdparty/*"
  boost_test_macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: >
          CI/check_boost_test_macro.sh
  smearing_config:
    runs-on: ubuntu-latest
    container: python:alpine3.6
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: >
          CI/check_smearing_config.py .
