name: Release PR

on:
  pull_request:

jobs:
  process_release_pr:
    runs-on: ubuntu-latest
    if: >- 
      (
        (github.base_ref == 'releases' || startsWith(github.base_ref, 'release/')) 
        && github.event.pull_request.head.repo.full_name == github.repository 
      )
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r CI/release_requirements.txt
      - name: Run release script
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: CI/release.py pr-action --fail
